name: prime workflow
on:
  workflow_dispatch:

jobs:
  # create-matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     env: ${{ steps.matrix.outputs.env }}
  #   steps:
  #     - name: create matrix
  #       id: matrix
  #       shell: bash
  #       run: |
  #         matrix='[{"env":"one","env":"two","env":"three"}]'
  #         echo "env=$matrix" >> $GITHUB_OUTPUT

  call_second_flow:
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ one, two, three ]
      fail-fast: false
    uses: thomwiggs/experiments/.github/workflows/callme.yml@main
    with:
      env: ${{ matrix.env }}
    # needs: create-matrix

    # steps:
    #   - name: call second workflow
    #     uses: thomwiggs/experiments/.github/workflows/callme.yml@main
