name: prime workflow
on:
  workflow_dispatch:

jobs:
  # create-matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     env: ${{ steps.matrix.outputs.env }}
  #   steps:
  #     - name: create matrix
  #       id: matrix
  #       shell: bash
  #       run: |
  #         matrix='[{"env":"one","env":"two","env":"three"}]'
  #         echo "env=$matrix" >> $GITHUB_OUTPUT

  call_second_flow:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: thomwiggs/experiments/.github/workflows/callme.yml@main
    with:
      env: ${{ matrix.target }}
