name: prime workflow
on:
  workflow_dispatch:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: create matrix
        id: matrix
        shell: bash
        run: |
          matrix='[{"env":"one","env":"two","env":"three"}]'
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  call_second_flow:
    # runs-on: ubuntu-latest
    uses: thomwiggs/experiments/.github/workflows/callme.yml@main
    # needs: create-matrix
    # strategy:
    #   matrix:
    #     env: ${{ fromJson(needs.create-matrix.outputs.matrix) }}
    #   fail-fast: false

    # steps:
    #   - name: call second workflow
    #     uses: thomwiggs/experiments/.github/workflows/callme.yml@main
